- name: backend server setup
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present 

  - name: create ansible user
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download the backend application code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip backend code     
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: npm install
    community.general.npm:
      path: /app    








